Move uploading and downloading of artifacts to workflow
It failed with the cryptic:
```
Prepare all required actions
Getting action download info
Error: Missing download info for actions/download-artifact@v2
```

Before; I'm guessing this needs to be at the workflow level for
it to be visible.