Remove test-summary action from the nightly workflow
This summary fails with:
Error: Cannot create a string longer than 0x1fffffe8 characters

This was supposed to be fixed with: #3119 but I forgot to update
the nightly workflow.