Improve assertion RecordLayerStoreCatalogTestBase.testListSchemasEmptyResult
The way it was running, if there was ever more than one schema, it
would fail with:
```
java.sql.SQLException: Continuation can only be returned once the result set has been exhausted
```
which is not particularly informative.