Make FDBDatabaseTest.testPostCloseHookFailsToCreate not flaky (#3908)
I saw two failures of this test:

https://github.com/FoundationDB/fdb-record-layer/actions/runs/21620783294
```
org.opentest4j.AssertionFailedError: expected: java.util.ImmutableCollections$Set12@a37a150<[foo]> but was: java.util.HashSet@77ab77ef<[foo]>
	at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
	at app//com.apple.foundationdb.record.provider.foundationdb.FDBDatabaseTest.testPostCloseHookFailsToCreate(FDBDatabaseTest.java:454)
```

and

https://github.com/FoundationDB/fdb-record-layer/actions/runs/21634337782?pr=3832
```
FDBDatabaseTest > testPostCloseHookFailsToCreate()
org.opentest4j.AssertionFailedError: expected: <[foo]> but was: <[]>
	at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
	at app//com.apple.foundationdb.record.provider.foundationdb.FDBDatabaseTest.testPostCloseHookFailsToCreate(FDBDatabaseTest.java:454)
```

The issue was that the future for `foo` would be scheduled, but may not
execute until the middle of the `assertEquals`, this means that
sometimes it would compare the sets before `foo` gets added, but log the
failure after `foo` was added (the first failure above), and sometimes
it would complete the entire assertion beforehand.


We don't actually depend on the future being run in a future, so I
changed it to not.
This was failing reliably, locally if I did `@RepeatedTest(100)`, and
with the change, it does not.